@startuml
skinparam backgroundColor #434343
skinparam defaultFontName Avenir
skinparam defaultFontColor #FFFFFF
skinparam defaultFontSize 26 
skinparam ArrowColor #ef9600
skinparam ArrowFontSize 22

skinparam SequenceLifeLineBorderColor DeepSkyBlue
skinparam SequenceLifeLineBackgroundColor DeepSkyBlue

skinparam ActorBackgroundColor #92c1e9
skinparam ActorBorderColor #edeff0

skinparam ParticipantBackgroundColor #92c1e9
skinparam ParticipantBorderColor #edeff0
skinparam ParticipantFontColor #2f3e4b

skinparam NoteBackgroundColor #2f3e4b
skinparam NoteBorderColor #edeff0
skinparam NoteFontSize 60

actor Alice
collections "Source Control" as Source
actor Susan
collections Build
collections Acceptance
actor Elizabeth
collections Staging 
collections "Pre-Prod" as Preprod
collections Production
actor "$$$" as dollars

Alice <- Source : Checkout Project
Alice <- Alice : Build/Test Software
Alice -> Source : Submit Change
Source -> Source : Build/Run Software
Susan -> Source : Approve Change
Source -> Build : Create Artifact
note over Alice, Production
    The artifact must work in all these places
end note
Build -> Acceptance : Update Channel
Acceptance -> Acceptance : Deploy
dollars -> Acceptance : Check out the dope feature
dollars -> Elizabeth : I love it
Elizabeth -> Acceptance : Ship it!
Acceptance -> Staging : Update Channel
Staging -> Staging : Deploy
Staging -> Preprod : Update Channel
Preprod -> Preprod : Deploy
Preprod -> Production : Update Channel
Production -> Production : Deploy
dollars -> Production : Be Stoked
@enduml