@startuml
!include theme.puml

skinparam NoteFontSize 60

actor Alice
collections "Source Control" as Source
actor Susan
collections Build
collections Acceptance
actor Elizabeth
collections Staging 
collections "Pre-Prod" as Preprod
collections Production
actor "$$$" as dollars

activate Acceptance
activate Staging
activate Preprod
activate Production
Alice <- Source : Checkout Project
Alice <- Alice : Build/Test Software
Alice -> Source : Submit Change
Source -> Source : Build/Run Software
Susan -> Source : Approve Change
Source -> Build : Create Artifact
Build -> Acceptance : Update Channel
note over Acceptance, Production
    Atomic Channels
end note
Acceptance -> Acceptance : Deploy
dollars -> Acceptance : Check out the dope feature
dollars -> Elizabeth : I love it
Elizabeth -> Acceptance : Ship it!
Acceptance -> Staging : Update Channel
Staging -> Staging : Deploy
Staging -> Preprod : Update Channel
Preprod -> Preprod : Deploy
Preprod -> Production : Update Channel
Production -> Production : Deploy
dollars -> Production : Be Stoked
@enduml